# Generated by Django 2.1.3 on 2019-02-08 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20190206_0300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id', '-timestamp', '-updated']},
        ),
    ]
